name: Scrape data from Austin Energy outage map

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch data
      run: pipx run kubra -- dd9c446f-f6b8-43f9-8f80-83f5245c60a1 76446308-a901-4fa3-849c-3dd569933a51 > outages.geojson
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
